# Generated by Django 5.1.1 on 2024-09-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0004_laundry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
