# Generated by Django 5.1.1 on 2024-09-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0005_alter_laundry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
