# Generated by Django 5.1.1 on 2024-09-05 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0006_alter_laundry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
